### ISSUE TITLE
Lifetimes not supported in type paths

### ISSUE THREAD

**Issue by RafDevX** [paholg/subenum#48]
For example,
```rs
#[subenum(Fruit)]
enum Food<'a> {
    Pizza,
	#[subenum(Fruit)]
	Apple,
    #[subenum(Fruit)]
    Banana(Yellow<'a>),
    Corn(Yellow<'a>),
}
```
this fails to compile because:
```
error[E0261]: use of undeclared lifetime name `'a`
   |
20 | #[subenum(Fruit)]
   |                - help: consider introducing lifetime `'a` here: `<'a>`
...
26 |     Banana(Yellow<'a>),
   |                   ^^ undeclared lifetime
```

It seems like `subenum` only supports references, e.g. `&'a str`. If it's not possible to detect when lifetimes are used in other scenarios, please provide the option of manually specifying what lifetimes are needed for a subenum, for example.

This is critical to my workflow, which unfortunately means I cannot use the crate without this feature, but thank you nevertheless for all your work.

**Comment by RafDevX** [comment]
I can confirm that at least the simple example provided above now works on 1.1.3, so I'll tentatively close this. Thank you for the update!
